### ISSUE TITLE
[Bug]:  oloot table error

### ISSUE THREAD

**Issue by wackoamd1** [ejektaflex/Bountiful#162]
### What happened?

i found this is my (server) log .
<html>
<body>

Couldn't parse loot table bountiful:blocks/bountyboard
--
com.google.gson.JsonSyntaxException: Missing type, expected to find a string
at net.minecraft.class_3518.method_15265(class_3518.java:112) ~[server-intermediary.jar:?]

</body>
</html>

### Mod Version

2.0.1

### Forge Version

fabric 1.12.2

### Relevant log output

<html>
<body>

[01:19:40] [Worker-Main-4/ERROR]: Couldn't parse loot table bountiful:blocks/bountyboard
--
com.google.gson.JsonSyntaxException: Missing type, expected to find a string
at net.minecraft.class_3518.method_15265(class_3518.java:112) ~[server-intermediary.jar:?]
at net.minecraft.class_134$class_136.method_605(class_134.java:112) ~[server-intermediary.jar:?]
at net.minecraft.class_134$class_136.method_530(class_134.java:101) ~[server-intermediary.jar:?]
at net.minecraft.class_120$class_123.method_528(class_120.java:99) ~[server-intermediary.jar:?]
at net.minecraft.class_120$class_123.method_517(class_120.java:88) ~[server-intermediary.jar:?]
at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[server-intermediary.jar:?]
at net.minecraft.class_85$class_90.method_441(class_85.java:149) ~[server-intermediary.jar:?]
at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[server-intermediary.jar:?]
at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[server-intermediary.jar:?]
at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[server-intermediary.jar:?]
at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
at net.minecraft.class_3518.method_15272(class_3518.java:456) ~[server-intermediary.jar:?]
at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[server-intermediary.jar:?]
at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[server-intermediary.jar:?]
at net.minecraft.class_52$class_54.method_340(class_52.java:213) ~[server-intermediary.jar:?]
at net.minecraft.class_52$class_54.deserialize(class_52.java:209) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.8.jar:?]
at net.minecraft.class_60.method_20711(class_60.java:44) ~[server-intermediary.jar:?]
at dev.latvian.mods.kubejs.core.LootTablesKJS.applyKJS0(LootTablesKJS.java:38) ~[kubejs-fabric-1801.4.0-build.249.jar:?]
at net.minecraft.class_60.redirect$bpb000$applyKJS(class_60.java:1521) ~[server-intermediary.jar:?]
at net.minecraft.class_60.method_20712(class_60.java:42) ~[server-intermediary.jar:?]
at net.minecraft.class_60.method_18788(class_60.java:17) ~[server-intermediary.jar:?]
at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

</body>
</html>

**Comment by ejektaflex** [comment]
#161
