### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by AdaraChristine** [ejektaflex/Bountiful#18]
Time: 1/1/19 7:21 PM
Description: Ticking block entity

java.lang.Exception: Bounty registry has fewer items than the max number of bounty items that the config dictates you could give!
	at ejektaflex.bountiful.logic.BountyCreator.create(BountyCreator.kt:47)
	at ejektaflex.bountiful.item.ItemBounty.ensureBounty(ItemBounty.kt:107)
	at ejektaflex.bountiful.logic.BountyCreator.createStack(BountyCreator.kt:28)
	at ejektaflex.bountiful.logic.BountyHolder.addSingleBounty(BountyHolder.kt:41)
	at ejektaflex.bountiful.logic.BountyHolder.update(BountyHolder.kt:64)
	at ejektaflex.bountiful.block.TileEntityBountyBoard.func_73660_a(TileEntityBountyBoard.kt:91)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by AdaraChristine** [comment]
Fixed by deleteing configs on server and client. Which means your configs are not updating with new versions.

**Comment by AdaraChristine** [comment]
Still crashing
Description: Ticking block entity

java.lang.Exception: Bounty registry has fewer items than the max number of bounty items that the config dictates you could give!
	at ejektaflex.bountiful.logic.BountyCreator.create(BountyCreator.kt:47)
	at ejektaflex.bountiful.item.ItemBounty.ensureBounty(ItemBounty.kt:107)
	at ejektaflex.bountiful.logic.BountyCreator.createStack(BountyCreator.kt:28)
	at ejektaflex.bountiful.logic.BountyHolder.addSingleBounty(BountyHolder.kt:41)
	at ejektaflex.bountiful.logic.BountyHolder.update(BountyHolder.kt:64)
	at ejektaflex.bountiful.block.TileEntityBountyBoard.func_73660_a(TileEntityBountyBoard.kt:91)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

https://pastebin.com/PwSrkUmN

**Comment by ejektaflex** [comment]
This was mentioned in the [changelog](https://minecraft.curseforge.com/projects/bountiful/files/2654376) that was posted when you updated the mod, so you didn't follow the instructions on updating. `*.cfg` files do update with new versions, though I really shouldn't be forcing people's `*.json` files to update when a new update comes out - considering the fact that the data is expected to be modified by the end user, there's no way for me to verify whether or not their config data is out of date. That's why I posted the notes in the changelog.
