### ISSUE TITLE
[Bug]: Crash when selecting bounty after add Embeddium mod

### ISSUE THREAD

**Issue by ColaLiao** [ejektaflex/Bountiful#251]
### What happened?

after add Embeddium mod

https://www.curseforge.com/minecraft/mc-mods/embeddium

selecting bounty crash the game

### How can we reproduce it?

use both Embeddium and Bountiful

### Mod Version

6.0.3

### Mod Loader

Forge

### Mod Loader Version

47.1.46

### Relevant log output

[debug.log](https://github.com/ejektaflex/Bountiful/files/12806493/debug.log)

[latest.log](https://github.com/ejektaflex/Bountiful/files/12806494/latest.log)

i don't know which one can help

**Comment by ejektaflex** [comment]
```
java.lang.NullPointerException: Cannot invoke "com.aetherteam.aether.api.registers.MoaType.getId()" because "moaType" is null
```
It seems here that your crash (at least in this log) isn't from Bountiful, but rather some mod dealing with an Aether dimension. Is there a different log that shows what you're talking about?

**Comment by ColaLiao** [comment]
> ```
> java.lang.NullPointerException: Cannot invoke "com.aetherteam.aether.api.registers.MoaType.getId()" because "moaType" is null
> ```
> 
> It seems here that your crash (at least in this log) isn't from Bountiful, but rather some mod dealing with an Aether dimension. Is there a different log that shows what you're talking about?

IDK, but the crash is after i add Embeddium mod, and the Not Enough Crash mod show me the crash is from Bountiful and Kambrik.

**Comment by ejektaflex** [comment]
Actually, it seems there is a problem. However, I'm not at a computer so I can't spend a lot of time looking into this until after I return from vacation.

There's a good chance it just might "not work" with Embeddium, but we'll see.

**Comment by ColaLiao** [comment]
I don't know why, but after I restart the game several times, the problem has gone, maybe that's good news?

**Comment by Opiboble** [comment]
Hello, 

Just wanted to report that I am running into this same issue I think.

Player accepts a bounty, puts it in their hot bar, and then looks at it. Boom kicked. 

I have Aether, Embeddium and Bountiful in my mod pack. 

If I remove Aether, no issue. If I remove Embeddium, no issue. 
Single player, no issue. Single player w/Lan and players connected, no issue. 
Only on a dedicated server do I have issues. 


So not sure what is going on to cause this issue. 

Here is the log snapshot. Let me know if you need anything else to track this down. : )


`[07Jan2024 15:13:14.564] [Server thread/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[07Jan2024 15:13:14.565] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 9
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		2: NORMAL
		3: ASM: class com.aetherteam.aether.event.listeners.EntityListener onRiderTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		4: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onPlayerTraveling(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		5: ASM: class dev.ghen.thirst.content.thirst.PlayerThirstManager onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$1553/0x000002bcbe6f0000@7e5c088a
		7: ASM: com.github.alexmodguy.alexscaves.server.event.CommonEvents@40244a03 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		8: ASM: class com.ibarnstormer.gbd.event.ModEvents playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		9: ASM: class net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		10: ASM: class net.mcreator.createsweetsandtreets.procedures.HoldTheRainbowProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		11: ASM: xaero.map.events.FMLCommonEvents@34a3e1c3 handlePlayerTickStart(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		12: ASM: xaero.common.events.FMLCommonEventHandler@78093f4c handlePlayerTickStart(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		13: ASM: class com.simibubi.create.content.equipment.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		14: ASM: class com.momosoftworks.coldsweat.util.compat.CompatManager tickCurios(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		15: ASM: class com.momosoftworks.coldsweat.common.event.TempEffectsCommon onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		16: ASM: class com.momosoftworks.coldsweat.common.event.ArmorInsulation addLeatherModifiers(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		17: ASM: class com.momosoftworks.coldsweat.common.capability.ItemInsulationManager onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		18: ASM: class com.momosoftworks.coldsweat.common.capability.EntityTempManager onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		19: ASM: class com.momosoftworks.coldsweat.common.capability.EntityTempManager playerRiding(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		20: ASM: de.maxhenkel.camera.ServerEvents@532e91a0 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		21: ASM: mekanism.common.CommonPlayerTickHandler@4e0e262 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		22: ASM: class com.momosoftworks.coldsweat.core.event.TaskScheduler runScheduledTasks(Lnet/minecraftforge/event/TickEvent;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/bountiful@6.0.3+1.20.1/io.ejekta.bountiful.content.BountyItem.m_7626_(BountyItem.java:35)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:580)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41611_(ItemStack.java:911)
	at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.execute(SugarCookiePropertyValueProviderProcedure.java:30)
	at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.onPlayerTick(SugarCookiePropertyValueProviderProcedure.java:19)
	at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.__SugarCookiePropertyValueProviderProcedure_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:920)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:285)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.mixinextras$bridge$m_9240_$116(ServerGamePacketListenerImpl.java)
	at TRANSFORMER/neruina@1.3.0/com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickPlayer$notTheCauseOfTickLag(NeruinaTickHandler.java:63)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.wrapOperation$zpp000$catchTickingPlayer(ServerGamePacketListenerImpl.java:3796)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:842)

[07Jan2024 15:13:14.940] [Server thread/WARN] [neruina/]: Neruina Caught Exception
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.mixinextras$bridge$m_9240_$116(ServerGamePacketListenerImpl.java) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickPlayer$notTheCauseOfTickLag(NeruinaTickHandler.java:63) ~[neruina-1.3.0-forge+1.18.2-1.20.1.jar%23382!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.wrapOperation$zpp000$catchTickingPlayer(ServerGamePacketListenerImpl.java:3796) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at io.ejekta.bountiful.content.BountyItem.m_7626_(BountyItem.java:35) ~[Bountiful-6.0.3+1.20.1-forge.jar%23279!/:?]
	at net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:580) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.world.item.ItemStack.m_41611_(ItemStack.java:911) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.execute(SugarCookiePropertyValueProviderProcedure.java:30) ~[Create%20Sweets%20And%20Treats%201.1.1.jar%23298!/:?]
	at net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.onPlayerTick(SugarCookiePropertyValueProviderProcedure.java:19) ~[Create%20Sweets%20And%20Treats%201.1.1.jar%23298!/:?]
	at net.mcreator.createsweetsandtreets.procedures.__SugarCookiePropertyValueProviderProcedure_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[Create%20Sweets%20And%20Treats%201.1.1.jar%23298!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:920) ~[forge-1.20.1-47.2.0-universal.jar%23430!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23425!/:?]
	... 12 more
[07Jan2024 15:13:14.966] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Opiboble lost connection: You have been kicked due to a ticking exception on your player. Please remove the culprit mod or contact an admin.
[07Jan2024 15:13:14.966] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Opiboble left the game`

**Comment by ejektaflex** [comment]
@Opiboble that's an issue with Create: Sweets & Treats, not Bountiful or Kambrik. It's been reported a lot since they both exist in the Perfect World modpack. :^)

**Comment by Opiboble** [comment]
Ah, well damn lol. Well since I have Pam's maybe I delete the sweets mod lol. Thank you for the quick response : )

**Comment by ejektaflex** [comment]
I've not received another report of this happening, and I cannot reproduce it. I'm inclined to think it might be another mod.
