### ISSUE TITLE
Game Crashes 

### ISSUE THREAD

**Issue by LuckyTuna** [ejektaflex/Bountiful#27]
Hello,

I am getting this error when I try to run minecraft 
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail"

I have tried various versions of Bountiful and Forgelin yet I get the same result. 

Here is important information:

Bountiful 2.1.0
Shadowfacts Forgelin-1.6.0 (because supposedly the newer versions have issues) 
1.12.2 Forge 1.12.2 - 14.23.4.2759

Here is the Crash Report 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.6.0.jar)
  OTGCorePlugin (OTG-Core.jar)
  IvToolkit (IvToolkit-1.12.jar)
  LoadingPlugin (Quark-r1.5-145.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  BetterFoliageLoader (Better-Foliage-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 1/25/19 8:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bountiful (bountiful)
Caused by: java.lang.NoClassDefFoundError: kotlin/random/Random
	at ejektaflex.bountiful.api.logic.pickable.PickableEntry.getRandCount(PickableEntry.kt:14)
	at ejektaflex.bountiful.api.logic.pickable.PickableEntry.pick(PickableEntry.kt:21)
	at ejektaflex.bountiful.api.logic.pickable.PickableEntry.isValid(PickableEntry.kt:25)
	at ejektaflex.bountiful.config.BountifulIO$hotReloadBounties$replaced$2.invoke(BountifulIO.kt:103)
	at ejektaflex.bountiful.config.BountifulIO$hotReloadBounties$replaced$2.invoke(BountifulIO.kt:16)
	at ejektaflex.bountiful.registry.ValueRegistry.replace(ValueRegistry.kt:36)
	at ejektaflex.bountiful.config.BountifulIO.hotReload(BountifulIO.kt:98)
	at ejektaflex.bountiful.config.BountifulIO.hotReloadBounties(BountifulIO.kt:102)
	at ejektaflex.bountiful.proxy.CommonProxy.postInit(CommonProxy.kt:85)
	at ejektaflex.bountiful.Bountiful.postInit(Bountiful.kt:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: kotlin.random.Random
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.2
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 385521424 bytes (367 MB) / 1946157056 bytes (1856 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 Optifine OptiFine_1.12.2_HD_U_C8 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version          | Source                                        | Signature                                |
	|:------ |:--------------------- |:---------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft             | 1.12.2           | minecraft.jar                                 | None                                     |
	| UCHIJ  | mcp                   | 9.42             | minecraft.jar                                 | None                                     |
	| UCHIJ  | FML                   | 8.0.99.99        | forge-1.12.2-14.23.4.2759.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                 | 14.23.4.2759     | forge-1.12.2-14.23.4.2759.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | ivtoolkit             | 1.3.3-1.12       | minecraft.jar                                 | None                                     |
	| UCHIJ  | otgcore               | 1.12.2 - v7      | minecraft.jar                                 | None                                     |
	| UCHIJ  | ambientsounds         | 2.0.0            | AmbientSounds v2.0.8 mc1.12.jar               | None                                     |
	| UCHIJ  | craftstudioapi        | 1.0.0            | CraftStudio-API-1.12.1.jar                    | None                                     |
	| UCHIJ  | harvestcraft          | 1.12.2w          | HarvestCraft-Mod-1.12.2.jar                   | None                                     |
	| UCHIJ  | openterraingenerator  | v6               | Open-Terrain-Generator-Mod-1.12.2.jar         | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UCHIJ  | twilightforest        | 3.8.689          | twilightforest-1.12.2-3.8.689-universal.jar   | None                                     |
	| UCHIJ  | animania              | 1.6.1            | animania-1.12.2-1.6.1.jar                     | None                                     |
	| UCHIJ  | antiqueatlas          | 4.4.9            | Antique-Atlas-Mod-1.12.2.jar                  | None                                     |
	| UCHIJ  | antiqueatlasoverlay   | 1.2              | Antique-Atlas-Mod-1.12.2.jar                  | None                                     |
	| UCHIJ  | examplemod            | 1.0              | Antique-Atlas-Mod-1.12.2.jar                  | None                                     |
	| UCHIJ  | jei                   | 4.9.1.168        | jei_1.12.2-4.9.1.168.jar                      | None                                     |
	| UCHIJ  | quark                 | r1.5-145         | Quark-r1.5-145.jar                            | None                                     |
	| UCHIJ  | autoreglib            | 1.3-24           | AutoRegLib-1.3-24.jar                         | None                                     |
	| UCHIJ  | betterfoliage         | 2.1.10           | Better-Foliage-Mod-1.12.2.jar                 | None                                     |
	| UCHIJ  | bibliocraft           | 2.4.5            | BiblioCraft-Mod-1.12.2.jar                    | None                                     |
	| UCHIJ  | biomebundle           | 5.1              | Biome_Bundle-1.12.2-v6.1.jar                  | None                                     |
	| UCHIJ  | bloodmoon             | 1.5.3            | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJ  | forgelin              | 1.6.0            | Forgelin-1.6.0.jar                            | None                                     |
	| UCHIEE | bountiful             | 2.1.0            | Bountiful-2.1.0.jar                           | None                                     |
	| UCHI   | codechickenlib        | 3.1.6.339        | CodeChickenLib-1.12.2.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | mantle                | 1.12-1.3.2.24    | Mantle-Mod-1.12.2.jar                         | None                                     |
	| UCHI   | tconstruct            | 1.12.2-2.10.1.87 | Tinkers-Construct-Mod-1.12.2.jar              | None                                     |
	| UCHI   | conarm                | 0.0.22-rc2       | Constructs-Armory-Mod-1.12.2.jar              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHI   | customspawner         | 3.11.4           | Custom-Mob-Spawner-Mod-1.12.2.jar             | None                                     |
	| UCHI   | customizeddungeonloot | 1.0.2            | Customized+Dungeon+Loot+1.12++(v.1.0.2).jar   | None                                     |
	| UCHI   | gottschcore           | 1.5.1            | GottschCore-mc1.12.2-f14.23.5.2768-v1.5.1.jar | None                                     |
	| UCHI   | dungeons2             | 1.3.3            | Dungeons2-mc1.12-f14.21.1.2387-v1.3.3.jar     | None                                     |
	| UCHI   | keepinginventory      | 2.4              | KeepingInventory-1.12.2-2.4.jar               | None                                     |
	| UCHI   | mocreatures           | 12.0.5           | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UCHI   | nei                   | 2.4.1            | Not-Enough-Items-1.12.2-Recommended.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI   | reccomplex            | 1.4.5            | RecurrentComplex-1.4.5.1.jar                  | None                                     |
	| UCHI   | reforged              | 0.7.5            | Reforged-Mod-1.12.jar                         | None                                     |
	| UCHI   | roguelike             | 1.7.2            | Roguelike-Dungeons-Mod-1.12.2.jar             | None                                     |
	| UCHI   | ruins                 | 17.1             | Ruins-1.12.2.jar                              | None                                     |
	| UCHI   | campfire              | 1.2              | Simple-Campfire-1.12.jar                      | None                                     |
	| UCHI   | spartanshields        | 1.3a             | Spartan-Shields-Mod-1.12.1.jar                | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.6.0.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
IvToolkit (IvToolkit-1.12.jar)
  
LoadingPlugin (Quark-r1.5-145.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
BetterFoliageLoader (Better-Foliage-Mod-1.12.2.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.4.7' Renderer: 'Intel HD Graphics 4000 OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 2.1 INTEL-12.4.7
	OpenGlRenderer: Intel HD Graphics 4000 OpenGL Engine
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by ejektaflex** [comment]
`ForgelinPlugin (Forgelin-1.6.0.jar)` - You are using an old version of Forgelin. My code uses Kotlin 1.3, which is only bundled into newer versions of Forgelin. If you are still getting an issue, post the new error in a new comment.

**Comment by Icebelly** [comment]
Just to add to this, I'm having the exact same issue with the newest version of Bountiful and Forgelin, the same kotlin/random/Random error even with kotlin 1.3/forgelin 1.8.2

**Comment by ejektaflex** [comment]
Huh, that's good to know. I'll see if there's a minimum Forge version that's needed to work and enforce it in the future. Thank you!

**Comment by ejektaflex** [comment]
I'm now compiling against Forge `14.23.5.2768` and don't see any runtime problems, so I'm not quite sure what the problem ever was (And that's the latest recommended version from October). Regardless, new versions will now check to ensure the Forge version is at least `14.23.5.2768` and at most `15.0.0.0`.
