### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by KaIiguIa** [ejektaflex/Bountiful#64]
## Bug Report

**Observed Behaviour**

What happened: game crashes

Crash log: [11mar2020 12:12:27.725] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, KaIiguIa, --version, 1.14.4-forge-28.2.0, --gameDir, C:\Users\Andrzej\AppData\Roaming\.minecraft\Oop, --assetsDir, C:\Users\Andrzej\AppData\Roaming\.minecraft\assets, --assetIndex, 1.14, --uuid, fdebe4b0ea2a3caca4a92c0c927ff1ee, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 28.2.0, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190829.143755]
[11mar2020 12:12:27.751] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 4.1.0+62+5bfa59b starting: java version 1.8.0_231 by Oracle Corporation
[11mar2020 12:12:28.082] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[11mar2020 12:12:28.084] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\Andrzej\AppData\Roaming\.minecraft\Oop\mods\OptiFine_1.14.4_HD_U_F4.jar
[11mar2020 12:12:28.645] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[11mar2020 12:12:28.945] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[11mar2020 12:12:30.488] [main/ERROR] [net.minecraftforge.fml.loading.LanguageLoadingProvider/]: Missing language kotlinfml version [1,) wanted by bountiful-3.0.0.jar
[11mar2020 12:12:31.660] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[11mar2020 12:12:31.715] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 244
[11mar2020 12:12:33.172] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[11mar2020 12:12:33.191] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.14.4-forge-28.2.0, --gameDir, C:\Users\Andrzej\AppData\Roaming\.minecraft\Oop, --assetsDir, C:\Users\Andrzej\AppData\Roaming\.minecraft\assets, --uuid, fdebe4b0ea2a3caca4a92c0c927ff1ee, --username, KaIiguIa, --assetIndex, 1.14, --accessToken, ????????, --userType, mojang, --versionType, release]
[11mar2020 12:12:38.517] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] *** Reflector Forge ***
[11mar2020 12:12:38.532] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[11mar2020 12:12:44.993] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.model.IModel.getTextures
[11mar2020 12:12:45.354] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] (Reflector) Class not present: net.minecraft.launchwrapper.Launch
[11mar2020 12:12:45.391] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.Loader
[11mar2020 12:12:46.366] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.SplashProgress
[11mar2020 12:12:46.382] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] *** Reflector Vanilla ***
[11mar2020 12:12:47.487] [Client thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: KaIiguIa
[11mar2020 12:13:07.130] [Client thread/WARN] [net.minecraft.client.GameSettings/]: Skipping bad option: lastServer:
[11mar2020 12:13:07.285] [Client thread/INFO] [net.minecraft.client.Minecraft/]: LWJGL Version: 3.2.2 build 10
[11mar2020 12:13:09.954] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] 
[11mar2020 12:13:09.955] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] OptiFine_1.14.4_HD_U_F4
[11mar2020 12:13:10.006] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] Build: 20191025-153543
[11mar2020 12:13:10.007] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] OS: Windows 7 (amd64) version 6.1
[11mar2020 12:13:10.007] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] Java: 1.8.0_231, Oracle Corporation
[11mar2020 12:13:10.007] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[11mar2020 12:13:10.008] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] LWJGL: 3.3.0 Win32 WGL EGL OSMesa VisualC DLL
[11mar2020 12:13:10.010] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] OpenGL: GeForce 7300 GS/PCIe/SSE2, version 2.1.2, NVIDIA Corporation
[11mar2020 12:13:10.015] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] OpenGL Version: 2.1.2
[11mar2020 12:13:10.654] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] Maximum texture size: 4096x4096
[11mar2020 12:13:10.747] [VersionCheck/INFO] [net.optifine.Config/]: [OptiFine] Checking for new version
[11mar2020 12:13:10.751] [Client thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] OpenGL Version: 2.1.2
[11mar2020 12:13:10.752] [Client thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Vendor:  NVIDIA Corporation
[11mar2020 12:13:10.752] [Client thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Renderer: GeForce 7300 GS/PCIe/SSE2
[11mar2020 12:13:10.753] [Client thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Capabilities:  2.0  2.1  -  -  - 
[11mar2020 12:13:10.803] [Client thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] GL_MAX_DRAW_BUFFERS: 4
[11mar2020 12:13:10.803] [Client thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[11mar2020 12:13:10.803] [Client thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[11mar2020 12:13:10.804] [Client thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] Load shaders configuration.
[11mar2020 12:13:10.810] [Client thread/INFO] [net.optifine.shaders.SMCLog/]: [Shaders] No shaderpack loaded.
[11mar2020 12:13:12.147] [VersionCheck/INFO] [net.optifine.Config/]: [OptiFine] Version found: F2
[11mar2020 12:13:12.776] [Client thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod File bountiful-3.0.0.jar needs language provider kotlinfml:1 or above to load
§7We have found none
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:63) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_231]
	at java.util.Collections$2.tryAdvance(Unknown Source) ~[?:1.8.0_231]
	at java.util.Collections$2.forEachRemaining(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:1.8.0_231]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_231]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:117) ~[?:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:146) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:454) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) ~[1.14.4-forge-28.2.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.2.0.jar:28.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
[11mar2020 12:13:13.335] [Client thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:454) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) ~[1.14.4-forge-28.2.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.2.0.jar:28.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
[11mar2020 12:13:17.581] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[11mar2020 12:13:18.034] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] *** Reloading textures ***
[11mar2020 12:13:18.034] [Client thread/INFO] [net.optifine.Config/]: [OptiFine] Resource packs: Mod Resources
[11mar2020 12:13:18.658] [Client thread/FATAL] [net.minecraft.client.Minecraft/]: Unreported exception thrown!
java.lang.ExceptionInInitializerError: null
	at svenhjol.charm.base.CharmAsmHooks.handleMusicTick(CharmAsmHooks.java:65) ~[?:1.14.4-1.5.2]
	at net.minecraft.client.audio.MusicTicker.func_73660_a(SourceFile) ~[?:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1351) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) ~[1.14.4-forge-28.2.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.2.0.jar:28.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
Caused by: java.lang.NullPointerException
	at svenhjol.meson.Meson.<init>(Meson.java:33) ~[?:1.14.4-1.5.2]
	at svenhjol.meson.Meson.<clinit>(Meson.java:26) ~[?:1.14.4-1.5.2]
	... 16 more
[11mar2020 12:13:21.122] [Client thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:100]: ---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 11.03.20 12:13
Description: Unexpected error

java.lang.ExceptionInInitializerError: null
	at svenhjol.charm.base.CharmAsmHooks.handleMusicTick(CharmAsmHooks.java:65) ~[?:1.14.4-1.5.2] {re:classloading}
	at net.minecraft.client.audio.MusicTicker.func_73660_a(SourceFile) ~[?:?] {re:classloading,xf:fml:charm:MusicTickerTick,xf:fml:charm:MusicTickerStop,xf:fml:charm:MusicTickerPlaying}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) ~[1.14.4-forge-28.2.0.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.2.0.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}
Caused by: java.lang.NullPointerException
	at svenhjol.meson.Meson.<init>(Meson.java:33) ~[?:1.14.4-1.5.2] {re:classloading}
	at svenhjol.meson.Meson.<clinit>(Meson.java:26) ~[?:1.14.4-1.5.2] {re:classloading}
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1406609768 bytes (1341 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		[1.14.2-1.14.4]TorchBowMod_v1.5.jar TorchBowMod {torchbowmod@1.5 NONE}
		Aquaculture-1.14.4-2.0.2.jar Aquaculture 2 {aquaculture@1.14.4-2.0.2 NONE}
		atmospheric-1.14.4-1.1.2.jar Atmospheric {atmospheric@1.1.2 NONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 NONE}
		betterbasicbiomesrelease1.jar Better Basic Biomes {better_basic_biomes@1.0.0 NONE}
		bountiful-3.0.0.jar Bountiful {bountiful@3.0.0 NONE}
		branders-enhanced-mob-spawners-v1.14.4-1.4.3.jar Enhanced Mob Spawners {spawnermod@1.4.4 NONE}
		branders-wellfedmod-1.14.4-1.2.0.jar Well Fed - quality food! {wellfedmod@1.2.0 NONE}
		ceilingtorch-1.14.4-v1.5.jar Ceiling Torch {ceilingtorch@v1.5 NONE}
		Charm-1.14.4-1.5.2.jar Charm {charm@1.14.4-1.5.2 NONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 NONE}
		cofh_core-1.14.4-0.2.0b.jar CoFH Core {cofh_core@0.2.0b NONE}
		compactores-1.14.4-1.0.0.jar Compact Ores {compactores@1.0.0 NONE}
		conjurerscookbook-0.0.1.jar Conjurer's Cookbook {conjurerscookbook@0.0.1 NONE}
		DungeonCrawl-1.14.4-1.5.2.jar Dungeon Crawl {dungeoncrawl@1.5.2 NONE}
		ensorcellation-1.14.4-0.2.0b.jar Ensorcellation {ensorcellation@0.2.0b NONE}
		extcaves-1.5.jar Extended Caves {extcaves@1.5 NONE}
		EyesInTheDarkness-1.14.4-0.2.0.jar Eyes in the Darkness {eyesinthedarkness@0.2.0 NONE}
		fimbulwinter-1.1.2.jar Fimbulwinter {fimbulwinter@1.1.2 NONE}
		fishtraps-0.0.4.jar Fish Traps {fishtraps@1.14.4-0.0.4 NONE}
		flamboyant-1.0.5.jar Flamboyant {flamboyant@1.0.5 NONE}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 NONE}
		gravestone-1.15.2.jar Gravestone Mod {gravestone@1.15.2 NONE}
		guardvillagers-1.14.4-1.0.2.jar Guard Villagers {guardvillagers@1.0.2 NONE}
		infernalmobs-1.14.4.6.jar Infernal Mobs {infernalmobs@1.14.4.6 NONE}
		invtweaks-1.14.4-1.0.1.jar Inventory Tweaks Reborn {invtweaks@1.14.4-1.0.1 NONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 NONE}
		lava-monster-1.14.4-1.0.2.jar Lava Monster {lava_monster@1.0.2 NONE}
		Ma-Enchants-1.14.4-1.8.1.jar Ma Enchants {ma-enchants@1.14.4-1.8.1 NONE}
		Menacing+Monsters+1.3.3.jar Menacing Monsters {menacing_monsters@1.3.3 NONE}
		morecharcoal-1.14.4-6.jar More Charcoal {morecharcoal@1.14.4-6 NONE}
		NaturesCompass-1.14.4-1.8.3.jar Nature's Compass {naturescompass@1.14.4-1.8.3 NONE}
		Neat+1.5-19.jar Neat {neat@1.5-19 NONE}
		NetehrOverhaul1.14.4Ver1.7.jar NetherUpdate {netherupdate@1.0.0 NONE}
		OresAboveDiamonds-1.14.4+v3.2.jar Ores Above Diamonds {oresabovediamonds@3.2 NONE}
		premium-wood-1.14.4-1.0.1.jar Premium Wood {premium_wood@1.0.1 NONE}
		ProgressiveBosses-2.1.4.jar Progressive Bosses {progressivebosses@2.1.4 NONE}
		Quark-r2.0-211.jar Quark {quark@r2.0-211 NONE}
		RefreshedNether+v.1.9+(1.14.4).jar Refreshed Nether {refreshed_nether@1.9.0 NONE}
		ruins-1.14.4.6.jar Ruins {ruins@1.14.4.6 NONE}
		SaveMyStronghold-1.14.4-1.0.0.jar Save My Stronghold! {savemystronghold@1.14.4-1.0.0 NONE}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 NONE}
		simplefarming-1.14.4-1.2.8.jar Simple Farming {simplefarming@1.14.4-1.2.8 NONE}
		simplybackpacks-1.14.4-1.4.0.jar Simply Backpacks {simplybackpacks@1.14.4-1.4.0 NONE}
		swampexpansion-1.4.8.jar Swamp Expansion {swampexpansion@NONE NONE}
		The-Endergetic-Expansion-1.14.4-v1.1.0.jar The Endergetic Expansion {endergetic@1.1.0 NONE}
		Tree-Chopper-Mod-1.14.4.jar TreeChoppin {treechoppin@1.1.0 NONE}
		VanillaTweaks-1.14.4.1.5.12.jar VanillaTweaks {vanillatweaks@1.14.4.1.5.12 NONE}
		vilnames_1.14-1.4.jar Villager Names {vilnames@1.4 NONE}
		voyage-1.0.0.jar Voyage {voyage@1.0.0 NONE}
		Waddles-1.14.4-0.8.3.jar Waddles {waddles@1.14.4-0.8.3 NONE}
		wandering_trapper-1.14.4-0.1.0.jar Wandering Trapper {wandering_trapper@0.1.0 NONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 NONE}
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 NONE}
	Launched Version: 1.14.4-forge-28.2.0
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce 7300 GS/PCIe/SSE2 GL version 2.1.2, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q9300 @ 2.50GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.2
	OpenGlRenderer: GeForce 7300 GS/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
[11mar2020 12:13:21.126] [Client thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:100]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Andrzej\AppData\Roaming\.minecraft\Oop\crash-reports\crash-2020-03-11_12.13.21-client.txt

**Minimal setup needed to reproduce**

- Forge version: 1.14.4 forge- 28.2.0
- Bountiful version: 1.14.4-bountiful-3.0.0
- Other mods: included in crash report

**Steps to reproduce**

How to recreate this: crash after opening the game

**Comment by ejektaflex** [comment]
`[11mar2020 12:12:30.488] [main/ERROR] [net.minecraftforge.fml.loading.LanguageLoadingProvider/]: Missing language kotlinfml version [1,) wanted by bountiful-3.0.0.jar`

`[11mar2020 12:13:12.776] [Client thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod File bountiful-3.0.0.jar needs language provider kotlinfml:1 or above to load
§7We have found none`

You need Kottle to run this, as stated on CurseForge - it allows mods written in Kotlin to run! You can get it [here](https://www.curseforge.com/minecraft/mc-mods/kottle/files), just make sure you choose the right version.

**Comment by Gunner76th** [comment]
@KaIiguIa   Next time, please be polite to others and either upload your file directly or use a pastebin like site. Other authors, as well as individuals coming here looking for resolution to problems do not want to spend 5 minutes scrolling down past your log report.
