### ISSUE TITLE
Decree Crashes 

### ISSUE THREAD

**Issue by Siberious** [ejektaflex/Bountiful#97]
## Bug Report

**Observed Behaviour**

What happened: Buying blank decrees from villagers or by being given one by a bounty, will give you an item that will crash your game upon mousing over it in an inventory.

Crash log: The game crashed whilst rendering screen
Error: kotlin.TypeCastException: null cannot be cast to non-null type net.minecraft.nbt.CompoundNBT

**Expected Behaviour**

What should have happened: Player should be able to operate decrees after obtaining them without risk of an immediate game crash.

**Minimal setup needed to reproduce**

- Forge version: 
- Bountiful version: 
- Other mods:

**Steps to reproduce**

How to recreate this: Find a villager or a bounty with offers of a decree. Upon obtaining, mouse over the decree in your inventory.

**Comment by ejektaflex** [comment]
Ah, interesting. If you could provide a log, that would be great! I think I know what's happening here.

**Comment by Siberious** [comment]
This is what appears in the crash report. I'm sure you can make something of this, you know a lot more than I do


---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/28/20 3:19 PM
Description: Rendering screen

kotlin.TypeCastException: null cannot be cast to non-null type net.minecraft.nbt.CompoundNBT
	at ejektaflex.bountiful.ext.ExtNBTKt.getUnsortedList(ExtNBT.kt:34) ~[?:1.15.2-3.1.1] {re:classloading}
	at ejektaflex.bountiful.item.ItemDecree.func_77624_a(ItemDecree.kt:57) ~[?:1.15.2-3.1.1] {re:classloading}
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:562) ~[?:?] {re:classloading,xf:fml:charm:ItemStack,xf:fml:quark:add-spacing-for-stack}
	at net.minecraft.client.gui.screen.Screen.getTooltipFromItem(Screen.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:blur:hookBackgroundColor,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.renderTooltip(Screen.java:116) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:blur:hookBackgroundColor,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_191948_b(ContainerScreen.java:149) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.HopperScreen.render(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:742) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:798) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:byg.mixins.json:client.MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.19.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/528012309.call(Unknown Source) [forge-1.15.2-31.2.19.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ejektaflex.bountiful.ext.ExtNBTKt.getUnsortedList(ExtNBT.kt:34)
	at ejektaflex.bountiful.item.ItemDecree.func_77624_a(ItemDecree.kt:57)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:562)
	at net.minecraft.client.gui.screen.Screen.getTooltipFromItem(Screen.java:121)
	at net.minecraft.client.gui.screen.Screen.renderTooltip(Screen.java:116)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_191948_b(ContainerScreen.java:149)
	at net.minecraft.client.gui.screen.HopperScreen.render(SourceFile:23)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:742)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.HopperScreen
	Mouse location: Scaled: (362, 165). Absolute: (725.000000, 330.000000)
	Screen size: Scaled: (800, 419). Absolute: (1600, 837). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Siberious_'/311, l='MpServer', x=337.71, y=77.00, z=-455.05]]
	Chunk stats: Client Chunk Cache: 529, 315
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -6557012347869491284
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (173,63,-177), Chunk: (at 13,3,15 in 10,-12; contains blocks 160,0,-192 to 175,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1952689 game time, 3152831 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/528012309.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2976835792 bytes (2838 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.19.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.19.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.19.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.19.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre23.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.19.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.19
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinforforge@1.2.2
		kotlinfml@1.5.2
	Mod List: 
		torchslabmod-1.15.2_v1.6.15.jar Torch Slab Mod {torchslabmod@1.6.15 DONE}
		gun-mod-0.16.1-1.15.2 (1).jar MrCrayfish's Gun Mod {cgm@0.16.1 DONE}
		endportalrecipe_1.15-2.1.jar End Portal Recipe {endportalrecipe@2.1 DONE}
		simplybeans-1.2.jar Simply Beans {simplybeans@1.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		enchantable-1.3.0-mc1.15.2.jar Enchantable {enchantable@1.3.0 DONE}
		worleycaves-1.15.2-1.6.0.jar Worley's Caves {worleycaves@1.15.2-1.6.0 DONE}
		futuremc-1.15.2-1.0.1.jar Future MC {futuremc@1.15.2-1.0.1 DONE}
		incontrol-1.15-4.0.3.jar InControl {incontrol@1.15-4.0.3 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Bamboo-Blocks-1.15.2-v1.4.0.jar Bamboo Blocks {bambooblocks@1.4.0 DONE}
		Buzzier-Bees-1.15.2-1.5.1.jar Buzzier Bees {buzzierbees@1.5.1 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Upgrade-Aquatic-1.15.2-v1.6.1.jar Upgrade Aquatic {upgrade_aquatic@1.6.1 DONE}
		strawgolem-1.15.2-1.7.1.jar Straw Golem {strawgolem@1.15.2-1.7.1 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		Bloomful-1.15.2-v1.4.0.jar Bloomful {bloomful@NONE DONE}
		extraboats-1.3.6-1.15.2.jar Extra Boats {extraboats@1.3.6 DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		TerraForged-1.15.2-0.0.14.jar TerraForged {terraforged@0.0.14 DONE}
		NeverNeededOrWanted-1.15.2-0.1.5.jar Never Needed Or Wanted {nnow@0.1.5 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		CookingForBlockheads_1.15.2-8.0.2.jar Cooking for Blockheads {cookingforblockheads@8.0.2 DONE}
		SereneSeasons-1.15.2-3.0.0.72-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.72 DONE}
		VanillaTweaks-1.15.2.1.5.27.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.27 DONE}
		MutantBeasts-1.15.2-1.0.7.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.7 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		WAWLA-1.15.2-3.0.2.jar WAWLA {wawla@3.0.2 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		guardvillagers-1.15.2-1.0.8.jar Guard Villagers {guardvillagers@1.0.7 DONE}
		EnhancedVanilla_Snapshot_20w23a-Forge-1.15.2.31.2.0.jar Enhanced Vanilla {enhancedvanilla@Snapshot 20w23a DONE}
		simpleplanes-1.15.2-2.0.3.0.jar Simple Planes {simpleplanes@2.0.3.0 DONE}
		ForgivingVoid_1.15.1-4.0.0.jar Forgiving Void {forgivingvoid@4.0.0 DONE}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		CraftTweaker-1.15.2-6.0.0.24.jar CraftTweaker {crafttweaker@6.0.0.24 DONE}
		Swamp-Expansion-1.15.2-v1.7.1.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.19-universal.jar Forge {forge@31.2.19 DONE}
		dragonmounts-1.0.3.jar Dragon Mounts Legacy {dragonmounts@1.0.3 DONE}
		structure-gel-api-1.15.2-1.1.0.jar Structure Gel API {structure_gel@1.1.0 DONE}
		RottenCreatures-1.15.2-0.9.7.jar Rotten Creatures {rotten_creatures@0.9.7 DONE}
		forge-1.15.2-31.2.19-client.jar Minecraft {minecraft@1.15.2 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		IamMusicPlayer-1.15.2-1.2.jar Iam Music Player {iammusicplayer@1.2 DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		pandoras_creatures-1.15.2-1.0.0.jar Pandoras Creatures {pandoras_creatures@1.15.2-1.0.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		dungeons-plus-1.15.2-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		RecallPotionMod-1.2.0.jar Recall Potion Mod {recall_potion_mod@1.0.0 DONE}
		Seeker-Compass-1.15.2.v1.0.0.jar Seeker Compass {seeker_compass@1.0 DONE}
		Atmospheric-1.15.2-1.4.0.jar Atmospheric {atmospheric@1.4.0 DONE}
		Bountiful-1.15.2-3.1.1.jar Bountiful {bountiful@1.15.2-3.1.1 DONE}
		paintings-1.15.2-7.0.0.0.jar Paintings ++ {paintings@1.14.4-6.0.1.5 DONE}
		pamhc2foodcore-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		collective-1.15.2-1.35.jar Collective {collective@1.35 DONE}
		autumnity-1.3.2-1.15.2.jar Autumnity {autumnity@1.3.2 DONE}
		polymorph-FORGE-1.15.2-0.7.jar Polymorph {polymorph@FORGE-1.15.2-0.7 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-244.jar Quark {quark@r2.1-244 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		EndReborn+[0.6.0].jar End: Reborn {endreborn@0.6.0 DONE}
		DoubleSlabs-1.15-2.4.5.jar Double Slabs {doubleslabs@2.4.5 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		vehicle-mod-0.44.1-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.44.1 DONE}
		wandering_trapper-1.15.2-0.1.1.jar Wandering Trapper {wandering_trapper@1.15.2-0.1.1 DONE}
		cobbler-1.5.1.jar Cobbler {cobbler@1.5.1 DONE}
		cfm-7.0.0-pre16-mc1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		productivebees-1.15.2-0.1.15.jar Productive Bees {productivebees@1.15.2-0.1.15 DONE}
		byg-1.0.10.jar Oh The Biomes You'll Go {byg@1.0.10 DONE}
		Charm-1.15.2-1.5.7.jar Charm {charm@1.15.2-1.5.7 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 DONE}
		BetterMineshaftsForge-1.15.2-1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3 DONE}
		thutcore-1.15.2-7.2.1.jar Thut Core {thutcore@7.2.1 DONE, thutcrafts@7.2.1 DONE}
		thuttech-1.15.2-8.2.2.jar Thut Elevators {thuttech@8.2.2 DONE}
		WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
	Launched Version: 1.15.2-forge-31.2.19
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 23.20.16.4973, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre23
	OptiFine Build: 20200607-215525
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 23.20.16.4973
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by ejektaflex** [comment]
Should be fixed in Bountiful 3.3.1 with commit 81dff72!
